### ISSUE TITLE
Save button works at FM-19 but not at FM-18

### ISSUE THREAD

**Issue by kraeff** [factus10/fm-htmleditor#2]
On FM-19 the file works perfectly! On FM-18, when pressing the "Save" button, gives the following error:

The file “FM-HTMLEditor.fmp12” could not be opened. Either the host is not available, or the file is not available on that host.

**Comment by kraeff** [comment]
Everything works correctly! The problem was that I had two versions of FM installed. In this case, FMP URL protocol is confused.

**Comment by carlstarus** [comment]
Hi there. I downloaded the sample file and it works beautifully on FM Pro 18 Adv. However, it doesn't save and I see there is a function missing in the script. See screenshot attached. Which function would that be? Thank you in advance for any help you can provide. Best regards,
Carl
![function-missing](https://user-images.githubusercontent.com/25885283/119953623-78f51e00-bf9e-11eb-9536-082c49a6995b.png)
