### ISSUE TITLE
Webviewer having issue for local image is not save

### ISSUE THREAD

**Issue by thangamoptimist** [factus10/fm-htmleditor#3]
Hi ,

I am using your file, very nice everything is good, But only local image file is not save please fix that one issues

**Comment by carlstarus** [comment]
Hi thangamoptimist, This is not 'MY' file. I copied it into my github to work on it and try to fix it, but haven't had time yet.
Cheers

**Comment by factus10** [comment]
Are you saying you put an image in the container and it did not save the image? If so, that's expected behavior.
